import { useEffect, useState, useCallback } from "react";
import type { ModelNode, ModelEdge } from "@mc/okf";
import type { BusinessGoal } from "../../state/goal";
import { buildFocus, getQuestions, type InsightQuestion } from "../../lib/questions";

interface QuestionsPanelProps {
  node: ModelNode;
  nodes: ModelNode[];
  edges: ModelEdge[];
  goal: BusinessGoal;
}

type State =
  | { kind: "loading" }
  | { kind: "ready"; questions: InsightQuestion[] }
  | { kind: "empty" }
  | { kind: "error" };

export function QuestionsPanel({ node, nodes, edges, goal }: QuestionsPanelProps) {
  const [state, setState] = useState<State>({ kind: "loading" });

  const run = useCallback(async (force: boolean) => {
    if (node.schema.length === 0 && !node.description?.trim()) {
      setState({ kind: "empty" });
      return;
    }
    setState({ kind: "loading" });
    try {
      const focus = buildFocus(nodes, edges, node.key);
      const questions = await getQuestions(focus, goal, { force });
      setState({ kind: "ready", questions });
    } catch {
      setState({ kind: "error" });
    }
  }, [node.key, node.schema.length, node.description, nodes, edges, goal]);

  useEffect(() => { void run(false); }, [run]);

  return (
    <div className="mt-4 pt-4 border-t border-[#d8dee8]">
      <div className="flex items-center gap-2 mb-[10px]">
        <h4 className="text-[11px] font-semibold text-slate-500 uppercase tracking-[0.3px] flex-1">Questions this unlocks</h4>
        <button
          onClick={() => void run(true)}
          className="text-[11px] text-[#4f46e5] hover:underline cursor-pointer"
        >
          Regenerate
        </button>
      </div>

      {state.kind === "loading" && (
        <div className="text-[12px] text-slate-400 italic">Generating questions…</div>
      )}
      {state.kind === "empty" && (
        <div className="text-[12px] text-slate-400 italic">Add fields or a description to this mart to unlock questions.</div>
      )}
      {state.kind === "error" && (
        <div className="text-[12px] text-slate-500">Couldn't generate questions — try Regenerate.</div>
      )}
      {state.kind === "ready" && (
        <ul className="flex flex-col gap-[10px]">
          {state.questions.map((q, i) => (
            <li key={i} className="text-[13px] text-slate-900 leading-[1.45]">
              {q.question}
              <span className="block text-[11px] text-slate-400 mt-[2px]">unlocked by {q.unlockedBy}</span>
            </li>
          ))}
        </ul>
      )}

      <p className="text-[10.5px] text-slate-400 leading-[1.4] mt-3">
        Generated by Google Gemini from mart titles, descriptions and field names. Row-level data is never sent.
      </p>
    </div>
  );
}
